services:
  php:
    image: ghcr.io/ramazantufekci/k8s-laravel/k8s-laravel-php:main
#    build:
#      context: .
#    volumes:
#      - ./:/var/www/html

  web:
    image: ramazannginx
#    working_dir: /var/www/html
#    volumes:
#      - ./:/var/www/html
#      - .docker/nginx/nginx_template_local.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "82:80"
  node:
    image: node:22
    user: node
    working_dir: /assets
    volumes:
      - ./:/assets
    command: npm run watch
  redis:
    image: redis:6
    volumes:
      - redisdata:/data
  db:
    image: postgres:18.1-alpine3.23
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_DB: "${DB_PASSWORD}"
    volumes:
      - postgresdata:/var/lib/postgresql
volumes:
  postgresdata:
  redisdata:
