name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push-nginx:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # 1) Repo'yu çek
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Docker Buildx kur
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3) GHCR için login
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4) İmaj ismini belirle
      - name: Extract metadata for Docker
        id: meta-nginx
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/k8s-laravel-nginx
          
      # 5) Docker image build ve push
      - name: Nginx Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./nginx/prod.Dockerfile
          push: true
          tags: ${{ steps.meta-nginx.outputs.tags }}
          labels: ${{ steps.meta-nginx.outputs.labels }}
          
  build-and-push-php:
    needs: build-and-push-nginx
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # 1) Repo'yu çek
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Docker Buildx kur
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3) GHCR için login
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4) İmaj ismini belirle
      - name: Extract metadata for Docker
        id: meta-php
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/k8s-laravel-php
          
      # 5) Docker image build ve push
      - name: Php Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./php/prod.Dockerfile
          push: true
          tags: ${{ steps.meta-php.outputs.tags }}
          labels: ${{ steps.meta-php.outputs.labels }}
